apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ibm-mq-lab
resources:
  - namespace.yaml
  - mq.yaml
configMapGenerator:
  - name: mq-lab-config
    files:
      - 20-lab.mqsc
